# Generated by Django 3.2.8 on 2021-10-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='family_name',
            field=models.CharField(default='others', help_text='family from skill belongs e.g. Frameworks', max_length=255, verbose_name='skill family name'),
        ),
    ]
